#ifndef PICO_BOARD_CONFIG_H_
#define PICO_BOARD_CONFIG_H_

#include "enums.pb.h"

#define BOARD_CONFIG_LABEL "cutebox"

#define GPIO_PIN_09 GpioAction::BUTTON_PRESS_UP
#define GPIO_PIN_28 GpioAction::BUTTON_PRESS_DOWN
#define GPIO_PIN_27 GpioAction::BUTTON_PRESS_RIGHT
#define GPIO_PIN_29 GpioAction::BUTTON_PRESS_LEFT

#define GPIO_PIN_25 GpioAction::BUTTON_PRESS_B1
#define GPIO_PIN_23 GpioAction::BUTTON_PRESS_B2
#define GPIO_PIN_26 GpioAction::BUTTON_PRESS_B3
#define GPIO_PIN_24 GpioAction::BUTTON_PRESS_B4

#define GPIO_PIN_13 GpioAction::BUTTON_PRESS_R1
#define GPIO_PIN_11 GpioAction::BUTTON_PRESS_R2
#define GPIO_PIN_12 GpioAction::BUTTON_PRESS_L1
#define GPIO_PIN_10 GpioAction::BUTTON_PRESS_L2

#define GPIO_PIN_00 GpioAction::BUTTON_PRESS_S1
#define GPIO_PIN_01 GpioAction::BUTTON_PRESS_S2
#define GPIO_PIN_04 GpioAction::BUTTON_PRESS_A1
#define GPIO_PIN_05 GpioAction::BUTTON_PRESS_A2
#define GPIO_PIN_03 GpioAction::BUTTON_PRESS_R3
#define GPIO_PIN_02 GpioAction::BUTTON_PRESS_L3

#define DEFAULT_SOCD_MODE SOCD_MODE_UP_PRIORITY
#define BUTTON_LAYOUT BUTTON_LAYOUT_STICKLESS
#define BUTTON_LAYOUT_RIGHT BUTTON_LAYOUT_NOIR8

#endif
